version: '3'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='EVN'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='thanh123'
      - MYSQL_ROOT_PASSWORD='thanh123'
      - MYSQL_HOST=''
    volumes:
      - /var/lib/mysql:/var/run/mysql
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysql:/run/mysql
    depends_on:
      - db